#!/usr/bin/env python3
"""Parent gate: synthetic loopback + current saved browser evidence, never real users."""
import hashlib
import json
from pathlib import Path
import subprocess
import sys

ROOT = Path(__file__).resolve().parent
PROJECT = ROOT.parent.parent


def require(condition, message):
    if not condition:
        raise ValueError(message)


def main():
    validator = Path.home() / '.agents/skills/handoff/validate.py'
    subprocess.run([sys.executable, str(validator), 'plan', str(ROOT / 'plan.json')], check=True, cwd=PROJECT)
    for task in ('receive-aggregate', 'send-retry', 'delivery-view'):
        subprocess.run([sys.executable, str(validator), 'result', str(ROOT / (task + '-result.json')), '--plan', str(ROOT / 'plan.json')], check=True, cwd=PROJECT)
    for script in (ROOT / 'test_receiver.py', ROOT / 'test_sender.py', ROOT / 'test_delivery_view.py', ROOT.parent / 'ai-pms-central/test_central.py'):
        subprocess.run([sys.executable, str(script)], check=True, cwd=PROJECT)
    subprocess.run([sys.executable, str(ROOT / 'exercise_transport.py')], check=True, cwd=PROJECT)
    evidence = json.loads((ROOT / 'acceptance-evidence.json').read_text())
    require(evidence['scope'] == 'A-local-transport', 'wrong scope')
    require(evidence['api_implementation_approved'] is True, 'missing approval A')
    require(evidence['local_loopback_verified'] is True, 'missing loopback proof')
    require(evidence['actual_multi_user_delivery_verified'] is False and evidence['product_complete'] is False, 'invalid completion claim')
    for check in ('multi_project_list', 'project_detail', 'original_event', 'search', 'heartbeat_only', 'delivery_failure', 'mobile_390', 'empty_state', 'delivery_state_unknown', 'central_read_failure'):
        require(evidence['browser_checks'].get(check) is True, 'missing browser observation: ' + check)
    required = {'spec.md', 'plan.json', 'approval.json', 'intent-review.json', 'common.py', 'receiver.py', 'sender.py',
                'test_receiver.py', 'test_sender.py', 'test_delivery_view.py', 'exercise_transport.py',
                'code-review.md', 'evidence/dashboard.html', 'evidence/empty.html', 'evidence/audit.html', 'evidence/error.html',
                'evidence/browser-observation.md', 'evidence/loopback-observation.json', 'evidence/generation.json'}
    require(set(evidence['file_hashes']) == required, 'missing required evidence')
    for name, value in evidence['file_hashes'].items():
        require(hashlib.sha256((ROOT / name).read_bytes()).hexdigest() == value, 'stale file: ' + name)
    require(hashlib.sha256((ROOT.parent / 'ai-pms-central/central.py').read_bytes()).hexdigest() == evidence['central_sha256'], 'stale central implementation')
    generation_bytes = (ROOT / 'evidence/generation.json').read_bytes()
    generation = json.loads(generation_bytes)
    code = {name: ROOT / name for name in ('common.py', 'receiver.py', 'sender.py', 'exercise_transport.py')}
    code['central.py'] = ROOT.parent / 'ai-pms-central/central.py'
    require(set(generation['code_hashes']) == set(code), 'incomplete generation code identity')
    for name, path in code.items():
        require(hashlib.sha256(path.read_bytes()).hexdigest() == generation['code_hashes'][name], 'HTML generated by different code')
    artifacts = {'dashboard.html', 'empty.html', 'audit.html', 'error.html', 'loopback-observation.json'}
    require(set(generation['artifact_hashes']) == artifacts, 'incomplete generation artifact identity')
    for name, value in generation['artifact_hashes'].items():
        require(hashlib.sha256((ROOT / 'evidence' / name).read_bytes()).hexdigest() == value, 'stale generated artifact')
    generation_hash = hashlib.sha256(generation_bytes).hexdigest()
    require(evidence['browser_generation_sha256'] == generation_hash, 'browser observed different generation')
    require('Generation receipt SHA-256: ' + generation_hash in (ROOT / 'evidence/browser-observation.md').read_text(), 'browser observation missing generation identity')
    print('LOCAL LOOPBACK TRANSPORT VERIFIED; real two-user app delivery UNVERIFIED; product INCOMPLETE')


if __name__ == '__main__':
    main()
